### ISSUE TITLE
Important modifications to be applied to Workshop 2

### ISSUE THREAD

**Issue by pedrohbraga** [QCBSRworkshops/workshop02#7]
Before developing and modifying this workshop, please read through the [presenter and developer protocol](https://qcbsrworkshops.github.io/presenter-developer-protocol/_book/developing-en.html#guidelines) **carefully** and refer back to it regularly as you work.

### Specific to adapting workshops to a remote framework:

- [x] **Fit this workshop to a 3-hour format**. The duration of this workshop should be ~3 hours (including exercises and one or two breaks of 5 minutes; excluding longer breaks). To fit this format, please add, edit, or **hide** slides from existing workshops. You can begin by hiding repetitive examples, non-essential slides, or some of the additional advanced slides that are included at the end of some workshops. Some workshops will be more difficult to shorten than others, due to their subject matter. It is not a problem to let these workshops run slightly over 3 hours to guarantee accurate and complete information. (Use your judgment). DO NOT delete slides. Use the `instruction: hidden_remote` tag. See an example below:

```
---
instruction: hidden_remote

# Slide title: I love statistics!

### Content: Amazing!
---
```
- [x] **Develop new or adapt current exercises to better suit the remote workshop format and the use of breakout rooms**. Exercises should be informative and engaging. Remember to leave time for students to work through exercises and ask questions. Refer to [these guidelines](https://qcbsrworkshops.github.io/presenter-developer-protocol/_book/developing-en.html#active-learning) to find suggestions of exercises promoting active learning. You may use additional resources to create the exercises.

### Specific to slide structure, grammar and style

- [x] **Ensure code is working correctly and that code matches workshop presentation**. Continue to check this as you make changes.

- [x] **Proofread correcting spelling, grammar, or punctuation errors**.

- [x] **Look for and correct the content of slides that overflow the screen**.

- [x] **Look for and correct prose that mentions function names, object names, package names and code chunks that do not use backticks**.

- [x] **Look for and correct unnecessary abbreviations (e.g. use do not instead of don’t).**

- [x] **Correct unnecessary long sentences**.

- [x] **Ensure that the slides are written in a consistent style, which helps with the flow of workshops and student understanding**. This is especially important when working collaboratively with other developers.

- [x] **Include presenter notes to the slides you modify**. You can write notes for yourself to read in the presenter mode (press the keyboard shortcut `p`). These notes are written under three question marks `???`. See the example below:

```
---
The content of this workshop is essential for your graduate studies.

???

Note: _The presenter should sing this slide to the participants_.
---
```
### Specific to the translation of this workshop

- [x] **Add and translate the modified content to the French version of the workshop**.

- [x] **Proofread and correct spelling, grammar and punctuation errors**.

- [x] **Correct unnecessary long sentences**.

### Specific to this workshop

- [x] Solve issue #10
- [x] Solve issue #5 . 
- [x] Solve issue #6  . 
- [x] About the workshop structure: Labeling the tidy content (`dplyr`, `tidyr`, and `maggritr`) as something for "advanced users" makes these tools seem less accessible, when that is not necessarily the case. This also breaks the workshop structure's logic, and makes this section seem separate from the rest of the workshop. In an effort to make this section less intimidating, it would be better to change this wording to focus on making the distinction between base R and the `tidyverse` sections of the workshop. Specifically, it can be important to briefly explain the contributions of the `tidy` packages (i.e. why use `dplyr` when most operations can be done in base R). This would help clarify the workshop structure, and would also be a great opportunity to make a fun "Welcome to the tidyverse" slide to introduce the tidy content 🤩.
- [x] Convert all `gather()` and `spread()` occurrences to `pivot_wider()` and `pivot_longer()`, because `gather()` and `spread()` are now retired. Argument names will also need to be changed (`key` and `value` have been replaced).
- [x] Update logos (see new `dplyr` logo [here](https://github.com/tidyverse/dplyr), `tidyr` logo [here](https://github.com/tidyverse/tidyr)).
- [x] Slide 39: Change `header = T` to `header = TRUE`, because using `T` is not recommended.
- [x] This workshop should (briefly) introduce the `tibble` structure in the `tidyverse` section.
- [x] Optional inspiration for a challenge: asking participants to do the same manipulation and summary operations using base R and their tidy equivalents, perhaps as a final challenge in groups. This could be a great way to show how the tidy approach can yield shorter code.

Only close this issue after all cases have been ticked and verified.

**Comment by linley-sherin** [comment]
### Issues to be addressed (added Feb 2021)

Both presentations
- [ ] Badges on slide 2 are out of data (need to be updated with the badges from the README)

English presentation
- [ ] Slides 73, 84, 85 and 112 have content overflow 
- [ ] Slide 73 shows some md notation/part of the code that should be invisible 
- [ ] Slide 14 has a spelling error

French presentation
- [ ] Slides 83, 84, 87, 89, 94 have content overflow
- [ ] Many slides do not match the English presentation (ex. slides 6, 9, 10, 11,14, 20, 21, 23, etc). The English one looks more up to date to the French version should be modified to match it.
